//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category_table()
        {
            this.Todo_table = new HashSet<Todo_table>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string name { get; set; }
    
        public virtual User_table User_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Todo_table> Todo_table { get; set; }
    }
}
