//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo_table
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<bool> archived { get; set; }
        public Nullable<bool> ok { get; set; }
        public bool ticket1 { get; set; }
        public bool ticket2 { get; set; }
        public bool ticket3 { get; set; }
        public Nullable<System.DateTime> creation_datetime { get; set; }
        public Nullable<System.DateTime> deadline_datetime { get; set; }
        public Nullable<System.DateTime> remember_datetime { get; set; }
        public Nullable<System.DateTime> repeat_time { get; set; }
    
        public virtual Category_table Category_table { get; set; }
    }
}
